/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import project.*;
/**
 *
 * @author nguye
 */

public class QLPhong extends javax.swing.JFrame {

    /**
     * Creates new form QLPhong
     */
    public QLPhong() {
        
        initComponents();
        
        
        //super.setLocationRelativeTo(null);
        // com bo box 
        String[] a ={"1 giuong don ","1 giuong doi","2 giuong don","2 giuong doi"};
        JComboBox c = new JComboBox(a);
        jTable1.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(c));
        String[] a1 ={"Standard ","Superior ","Deluxe","Suite"};
        JComboBox d = new JComboBox(a1);
        jTable1.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(d));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Xoa = new javax.swing.JMenuItem();
        Sua = new javax.swing.JMenuItem();
        Sua1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        Xoa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Xoa.setText("Xóa phòng");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Xoa);

        Sua.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Sua.setText("Cập nhật giá phòng");
        Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Sua);

        Sua1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Sua1.setText("Cập nhật trạng thái");
        Sua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sua1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Sua1);

        jMenuItem4.setText("jMenuItem4");
        jPopupMenu1.add(jMenuItem4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 204));
        setLocation(new java.awt.Point(215, 195));
        setMinimumSize(new java.awt.Dimension(1100, 550));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Danh sách phòng:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 164, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 30, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Số phòng");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 146, 71, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 181, 237, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Loại phòng");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 219, 86, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Số giường");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 291, 86, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard ", "Superior ", "Deluxe ", "Suite " }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 248, 237, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 giuong don ", "1 giuong doi", "2 giuong don", "2 giuong doi" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 326, 237, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Giá tiền/ngày");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 364, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 399, 237, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phòng", "Loại phòng", "Số giường", "giá tiền", "Trạng thái"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 120, 683, 350));

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, -1, -1));

        jLabel6.setFont(new java.awt.Font("Constantia", 3, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage room.png"))); // NOI18N
        jLabel6.setText("Quản lý phòng");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, 257, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin Home.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String roomNumber=jTextField1.getText();
        String roomType=(String) jComboBox1.getSelectedItem();
        String bed=(String) jComboBox2.getSelectedItem();
        String pricePerDay =jTextField2.getText();
        
        String query ="insert into room values ('" + roomNumber + "', '" + roomType + "', '" + bed + "', '" + pricePerDay + "', 'Not Booked')";
        InsertUpdateDelete.setData(query,"thêm thành công");
        setVisible(false);
        new QLPhong().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
         ResultSet rs = Select.getData("select * from room");
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try
        {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
//////////click chout
    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        if(evt.getButton() ==MouseEvent.BUTTON3){
            if(evt.isPopupTrigger()&&jTable1.getSelectedRowCount()!=0){
                jPopupMenu1.show(evt.getComponent(),evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jTable1MouseReleased

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        // TODO add your handling code here:
        int row =jTable1.getSelectedRow();
        if(row != -1){
            String roomNumber = jTable1.getValueAt(row, 0).toString();
            String sql ="DELETE FROM room WHERE roomNumber = '"+roomNumber+"'";
            try{
                int a = JOptionPane.showConfirmDialog(null, "Bạn muốn xóa phong "+roomNumber+"","Select",JOptionPane.YES_NO_OPTION);
            if(a == 0)
            {
                InsertUpdateDelete.setData("delete from  room where roomNumber = '"+roomNumber+"'", "Xóa thành công.");
                setVisible(false);
                new QLPhong().setVisible(true); 
            }
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_XoaActionPerformed

    private void SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        if(index != 1){
            String roomNumber = model.getValueAt(index, 0).toString();
           // String roomType = model.getValueAt(index, 1).toString();
           // String bed = model.getValueAt(index, 2).toString();
            String pricePerDay = model.getValueAt(index, 3).toString();
            //String status = model.getValueAt(index, 4).toString();
            
//            model.setValueAt(roomNumber, index, 0);
//            model.setValueAt(roomType, index, 1);
//            model.setValueAt(bed, index, 2);
//            model.setValueAt(pricePerDay, index, 3);
//            model.setValueAt(status, index, 4);
            
            String sql ="UPDATE room SET pricePerDay='"+pricePerDay+"' WHERE roomNumber = '"+roomNumber+"' ";
            try{
                int a = JOptionPane.showConfirmDialog(null, "Bạn Muon cap nhat gia phong "+roomNumber+"","Select",JOptionPane.YES_NO_OPTION);
            if(a == 0)
            {
                InsertUpdateDelete.setData("UPDATE room SET pricePerDay='"+pricePerDay+"' WHERE roomNumber = '"+roomNumber+"' ", "cap nhat gia phong thành công.");
                setVisible(false);
                new QLPhong().setVisible(true);
            }
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
            
        }
    }//GEN-LAST:event_SuaActionPerformed

    private void Sua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sua1ActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        if(index != 1){
            String roomNumber = model.getValueAt(index, 0).toString();
           // String roomType = model.getValueAt(index, 1).toString();
           // String bed = model.getValueAt(index, 2).toString();
           // String pricePerDay = model.getValueAt(index, 3).toString();
            String status = model.getValueAt(index, 4).toString();
            
            String sql ="UPDATE room SET status='"+status+"' WHERE roomNumber = '"+roomNumber+"' ";
            try{
                int a = JOptionPane.showConfirmDialog(null, "Bạn Muon cap nhat trang thai phong  "+roomNumber+"","Select",JOptionPane.YES_NO_OPTION);
            if(a == 0)
            {
                InsertUpdateDelete.setData("UPDATE room SET status='"+status+"' WHERE roomNumber = '"+roomNumber+"' ", "cap nhat trang thai thành công.");
                setVisible(false);
                new QLPhong().setVisible(true);
            }
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
            
        }
    }//GEN-LAST:event_Sua1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Sua;
    private javax.swing.JMenuItem Sua1;
    private javax.swing.JMenuItem Xoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
